SHOW TABLES;
DROP TABLE POST;
DROP TABLE MAP;
DROP TABLE MEMBER;

SELECT * FROM MEMBER;
SELECT * FROM POST;
SELECT * FROM MAP;

CREATE TABLE POST(
	PNO INT AUTO_INCREMENT PRIMARY KEY,
	MID VARCHAR(10) NOT NULL,
	TITLE VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(1000) NOT NULL,
	IMGNAME VARCHAR(100) NOT NULL,
	LOCATION VARCHAR(50) NOT NULL,
	PDATE DATETIME DEFAULT NOW()
);

CREATE TABLE MEMBER(
	MID VARCHAR(10) PRIMARY KEY,
	MPW VARCHAR(12) NOT NULL,
	MNAME VARCHAR(20),
	EMAIL VARCHAR(20),
	PROFILE VARCHAR(100) DEFAULT 'images\\pro.jpg'
);

CREATE TABLE MAP(
	PNO INT AUTO_INCREMENT PRIMARY KEY,
	LAT VARCHAR(20) NOT NULL,
	LNG VARCHAR(20) NOT NULL,
	LOCATION VARCHAR(50),
	MID VARCHAR(10),
	IMGNAME VARCHAR(100),
	CONSTRAINT mpno FOREIGN KEY (PNO) REFERENCES POST(PNO) ON DELETE CASCADE
);

insert into member values ('qwe','1212','경진','doingjinn@gmail.com',DEFAULT);
insert into member values ('qwqw','1212','에이','jogjin@hanmail.net',DEFAULT);
insert into member values ('asd','1212','hey','jgj1029@gmail.com',DEFAULT);
insert into post values (1, 'qwe', '11', 'dfsdfsd','\\img\\gj.jpg','LA',now());
select count(*) from post where mid='qwe';
update member set mpw='1212' where mid='qwe';
delete from member where mid='zzin';
delete from post where pno=1;

INSERT INTO POST (MID,TITLE,CONTENT,IMGNAME,LOCATION) VALUES (?,?,?,?,?);
INSERT INTO POST (MID,TITLE,CONTENT,IMGNAME,LOCATION) VALUES ('qwqw','oing','f,d','\\img\\gj.jpg','LA');
SELECT COUNT(*) FROM POST WHERE MID='qwqw';
SELECT A.* FROM (SELECT * FROM POST ORDER BY PNO DESC) A LIMIT 11, 20;
SELECT A.* FROM (SELECT B.* FROM (SELECT * FROM POST WHERE MID='qwqw' ORDER BY PNO DESC) B)A LIMIT 9,16;
SELECT A.* FROM (SELECT * FROM POST WHERE MID='qwqw' ORDER BY PNO DESC) A LIMIT 18,9;
SELECT A.* FROM (SELECT * FROM POST WHERE MID='qwe' ORDER BY PNO DESC) A;